feat(TTD): Implement mark tasks as completed
mohammed-sharraf-sazim/The-Todo pull request #10
Opened 2024-07-11 10:27 UTC by mohammed-sharraf-sazim

Description of the feature:
- Marked completed tasks
- Displayed the completed tasks at the bottom of the list
Associated Ticket Link(s):
- https://trello.com/c/UqJaGcMi/6-mark-tasks-as-completed

2024-07-11 15:12 UTC, nur-zaman-sazim approved these changes

2024-07-12 04:35 UTC, mMohsinSazim requested changes

2024-07-12 04:35 UTC, mMohsinSazim commented on src/components/TodoList.tsx
> +    if (a.isCompleted !== b.isCompleted){
unclear variable name...what is "a", "b" ? use meaningful variable naming convention

2024-07-12 04:35 UTC, mMohsinSazim commented on src/components/TodoList.tsx
> +    const aPriority = priorityOrder[a.priority ?? 'High']
same here....variable names are ambiguous

2024-07-14 12:50 UTC, mohammed-sharraf-sazim commented on src/components/TodoList.tsx
> +    const aPriority = priorityOrder[a.priority ?? 'High']
Changed all the variable names mentioned above

2024-07-14 16:03 UTC, mMohsinSazim approved these changes

2024-07-14 18:26 UTC, merged