feat(TTD): Filter task based on completion and priority
mohammed-sharraf-sazim/The-Todo pull request #12
Opened 2024-07-11 18:24 UTC by mohammed-sharraf-sazim

Description:
- Added filtering option to filter tasks based on priority (High, Medium and Low)
- Added filtering option to filter tasks based on completion (Active/Completed)

Associated Ticket Link(s):
-https://trello.com/c/MFh6HH9N/9-filter-tasks-active-completed
-https://trello.com/c/vIYNQtnE/10-filter-tasks-priority

2024-07-12 04:43 UTC, mMohsinSazim requested changes

2024-07-12 04:43 UTC, mMohsinSazim commented on src/App.tsx
> +      return task.priority === priorityFilter as Priority; // Cast to Priority
first remove the comment, also see how to implement this without using casting

2024-07-12 16:31 UTC, nur-zaman-sazim requested changes

2024-07-12 16:31 UTC, nur-zaman-sazim commented on src/components/FilterTasks.tsx
> +  priorityFilter: string | Priority;
`Priority`  is enough. No need to to use string.
If you need any more constants add it in the enum.

2024-07-12 16:31 UTC, nur-zaman-sazim commented on src/components/FilterTasks.tsx
> +                onClick={() => setPriorityFilter("all")}
Use an enum for priority filter.

2024-07-14 13:40 UTC, mohammed-sharraf-sazim commented on src/App.tsx
> +      return task.priority === priorityFilter as Priority; // Cast to Priority
Removed comments and implemented without casting

2024-07-14 13:42 UTC, mohammed-sharraf-sazim commented on src/components/FilterTasks.tsx
> +                onClick={() => setPriorityFilter("all")}
If I use enum I have to make some major changes.

2024-07-14 18:35 UTC, nur-zaman-sazim approved these changes

2024-07-14 18:46 UTC, merged