feat(TTD): Implement the due dates of a task
mohammed-sharraf-sazim/The-Todo pull request #13
Opened 2024-07-12 09:55 UTC by mohammed-sharraf-sazim

Description: 
- Implemented the functionality for users to add sue dates to a task.

Associated Ticket Link(s):
- https://trello.com/c/0TdnHChA/12-add-due-dates

2024-07-12 10:11 UTC, mMohsinSazim requested changes

2024-07-12 10:11 UTC, mMohsinSazim commented on src/App.tsx
> +          deadline: { from: new Date(), to: undefined },
without explicitly saying undefined, make that property optional

2024-07-12 10:11 UTC, mMohsinSazim commented on src/Model.ts
> +    deadline?: { from: Date | undefined; to: Date | undefined };
without explicitly saying undefined, make that property optional

2024-07-12 10:11 UTC, mMohsinSazim commented on src/components/SingleTask.tsx
> +  const [date, setDate] = React.useState<DateRange | undefined>(task.deadline);
use default export from React instead of React.useState

2024-07-12 10:25 UTC, mohammed-sharraf-sazim commented on src/Model.ts
> +    deadline?: { from: Date | undefined; to: Date | undefined };
Resolved the issue

2024-07-12 10:25 UTC, mohammed-sharraf-sazim commented on src/components/SingleTask.tsx
> +  const [date, setDate] = React.useState<DateRange | undefined>(task.deadline);
Resolved the issue

2024-07-14 10:02 UTC, mMohsinSazim approved these changes

2024-07-14 18:53 UTC, merged