feat(TTD): Filter tasks based on due dates
mohammed-sharraf-sazim/The-Todo pull request #14
Opened 2024-07-12 12:54 UTC by mohammed-sharraf-sazim

Description:
- Added the filtering option where users can filter based on due dates (Due Today, Upcoming, Overdue).

Associated Ticket Link(s):
- https://trello.com/c/fMZPIQtz/11-filter-tasks-due-dates

2024-07-12 16:38 UTC, nur-zaman-sazim requested changes

2024-07-12 16:38 UTC, nur-zaman-sazim commented on src/App.tsx
> +  const [dateFilter, setDateFilter] = useState<string>('all');
use Enum for date filters

2024-07-12 16:38 UTC, nur-zaman-sazim commented on src/App.tsx
>    });
Better to move the logics in a separate file

2024-07-14 10:01 UTC, mMohsinSazim requested changes
Why The comments are not addressed yet??

2024-07-14 13:43 UTC, mohammed-sharraf-sazim commented on src/App.tsx
> +  const [dateFilter, setDateFilter] = useState<string>('all');
If I use enum I have to make some major changes.

2024-07-14 13:49 UTC, mohammed-sharraf-sazim commented on src/App.tsx
>    });
This changed require some major refactoring

2024-07-14 19:35 UTC, mohammed-sharraf-sazim commented on src/App.tsx
>    });
Created a separate file for the logic

2024-07-14 20:19 UTC, nur-zaman-sazim approved these changes

2024-07-15 05:30 UTC, merged