feat(NTD): implementation of add tasks
mohammed-sharraf-sazim/The-Todo pull request #20
Opened 2024-07-18 06:52 UTC by mohammed-sharraf-sazim

Description: 
- Added the boilerplate code for redux for adding todos
- Added the functionality for adding tasks in a todo

Associated Trello Link(s):
- https://trello.com/c/otKRlEQE/14-redux-toolkit-implement

Developers Note:
In this PR it shows 14 files changed, but mostly are modification and installation of dependencies due to redux and shadcn installation. Thus making the PR big but actually there are only 3 files that are important and required a change. Those files are listed below: 
- modules/todo/components/TodoForm.tsx
- modules/todo/containers/TodoPageContainer.tsx
- modules/todo/models.ts

2024-07-26 16:00 UTC, mahir-mohsin-sazim requested changes

2024-07-26 16:00 UTC, mahir-mohsin-sazim commented on modules/todo/components/TodoForm.tsx
> +  const handleAdd = (event: React.FormEvent) => {
[FFT] instead of _handleAdd_ , won't it be better to rename it to _handleAddTask_

2024-07-26 16:00 UTC, mahir-mohsin-sazim commented on modules/todo/components/TodoForm.tsx
> +      console.log(result.data);
remove console.log please

2024-07-26 16:00 UTC, mahir-mohsin-sazim commented on modules/todo/components/TodoForm.tsx
> +      console.error(result.error);
same here....why errors are not handled properly??

2024-07-26 16:00 UTC, mahir-mohsin-sazim commented on shared/redux/store.ts
> +// src/shared/redux/store.ts
remove comments

2024-07-26 16:00 UTC, mahir-mohsin-sazim commented on shared/redux/reducers/todoSlice.ts
> +import { Todo } from "../../../modules/todo/models";
instead of using so many nested relative imports, use absolute path(EX: 
**"import {ToDo} from "@/modules/todo/models;"**
)

2024-07-26 16:00 UTC, mahir-mohsin-sazim commented on shared/redux/reducers/todoSlice.ts
> +    return []; // Handle case where localStorage is not available
remove comments

2024-07-26 16:00 UTC, mahir-mohsin-sazim commented on shared/redux/reducers/todoSlice.ts
> +    return; // Handle case where localStorage is not available
remove comments

2024-07-26 16:00 UTC, mahir-mohsin-sazim commented on shared/redux/hooks.ts
> +// src/shared/redux/hooks.ts
remove comments

2024-07-27 13:39 UTC, nur-zaman-sazim reviewed
add `"no-console": "warn",` to your .eslintrc

2024-07-28 12:52 UTC, mohammed-sharraf-sazim commented
> add `"no-console": "warn",` to your .eslintrc

Added

2024-07-28 13:24 UTC, nur-zaman-sazim commented
> > add `"no-console": "warn",` to your .eslintrc
> 
> Added

Added where ?

2024-07-29 08:00 UTC, mahir-mohsin-sazim approved these changes

2024-07-29 09:47 UTC, merged