feat(NTD): display of all the tasks
mohammed-sharraf-sazim/The-Todo pull request #21
Opened 2024-07-26 14:40 UTC by mohammed-sharraf-sazim

### Description of Change:

- Added the functionality to display all the tasks in /todo link.

### Associated Ticket Link(s):

- https://trello.com/c/CTS79DUe/3-creation-of-a-taskui

2024-07-26 16:05 UTC, mahir-mohsin-sazim requested changes
Please review your PR first

2024-07-26 16:05 UTC, mahir-mohsin-sazim commented on modules/todo/components/TodoForm.tsx
> +// import React, { useState } from "react";
remove comments

2024-07-26 16:05 UTC, mahir-mohsin-sazim commented on modules/todo/components/TodoForm.tsx
> +import { FormItem, Form, FormField, FormLabel, FormMessage } from "../../../shared/components/ui/form";
use absolute imports

2024-07-28 10:29 UTC, mohammed-sharraf-sazim commented on modules/todo/components/TodoForm.tsx
> +import { FormItem, Form, FormField, FormLabel, FormMessage } from "../../../shared/components/ui/form";
Resolved in PR#22.

2024-07-28 13:13 UTC, nur-zaman-sazim commented
> The above feedbacks are resolved in the PR#22.

Why is this fixed in another PR but not in this one ? 
you should fix thing in older (this) PR and then just rebase the other PR(s) if you make branches of this PR

2024-07-28 13:19 UTC, mohammed-sharraf-sazim commented
> > The above feedbacks are resolved in the PR#22.
> 
> Why is this fixed in another PR but not in this one ? you should fix thing in older (this) PR and then just rebase the other PR(s) if you make branches of this PR

SInce it was a minor change I did it in the following PR.

2024-07-28 13:31 UTC, nur-zaman-sazim commented
> > > The above feedbacks are resolved in the PR#22.
> > 
> > 
> > Why is this fixed in another PR but not in this one ? you should fix thing in older (this) PR and then just rebase the other PR(s) if you make branches of this PR
> 
> SInce it was a minor change I did it in the following PR.

major or minor we are getting familiar with the conventions so please let's try to follow that. Don't make PR(s) dependent on each other. 
Also linking PR is done by #PR_NUMBER like, #22

2024-07-28 14:00 UTC, mohammed-sharraf-sazim commented
> > > > The above feedbacks are resolved in the PR#22.
> > > 
> > > 
> > > Why is this fixed in another PR but not in this one ? you should fix thing in older (this) PR and then just rebase the other PR(s) if you make branches of this PR
> > 
> > 
> > SInce it was a minor change I did it in the following PR.
> 
> major or minor we are getting familiar with the conventions so please let's try to follow that. Don't make PR(s) dependent on each other. Also linking PR is done by #PR_NUMBER like, #22

Noted. I will keep that in mind.

2024-07-29 08:01 UTC, mahir-mohsin-sazim approved these changes

2024-07-29 10:52 UTC, merged