feat(NTD): set deadline and priority on a task
mohammed-sharraf-sazim/The-Todo pull request #25
Opened 2024-07-28 12:51 UTC by mohammed-sharraf-sazim

### Description of Change:
- Added the functionality to set deadline and priority on a task.
### Associated Ticket Link(s):
- https://trello.com/c/TZvb9fFd/4-set-priority
- https://trello.com/c/0TdnHChA/12-add-due-dates

2024-07-28 13:39 UTC, nur-zaman-sazim requested changes

2024-07-28 13:39 UTC, nur-zaman-sazim commented on .eslintrc.json
please look into how to add eslint rules
https://eslint.org/docs/latest/use/configure/rules

2024-07-28 13:39 UTC, nur-zaman-sazim commented on .eslintrc.json
>  }
{
  "extends": "next/core-web-vitals",
  "rules": {
    "no-console": "warn"
  }
}

2024-07-29 07:35 UTC, mohammed-sharraf-sazim commented on .eslintrc.json
>  }
Added in the eslint file

2024-07-29 12:39 UTC, merged