feat(TTD)#4: Implement the priority of a task
mohammed-sharraf-sazim/The-Todo pull request #8
Opened 2024-07-11 09:59 UTC by mohammed-sharraf-sazim

Description of the feature:
- Assigned a priority to a task (High, Medium or Low)
- Displayed task in a list from highest to lowest priority
Associated Ticket Link(s):
- https://trello.com/c/TZvb9fFd/4-set-priority
- https://trello.com/c/dmasfCEy/5-display-task-list

2024-07-11 15:09 UTC, nur-zaman-sazim requested changes

2024-07-11 15:09 UTC, nur-zaman-sazim commented on src/components/SingleTask.tsx
> +    const updateTasks = tasks.map((t) =>
Don't use single letter variable names.

2024-07-11 18:25 UTC, mohammed-sharraf-sazim commented on src/components/SingleTask.tsx
> +    const updateTasks = tasks.map((t) =>
Resolved this issue in PR#12.

2024-07-12 04:33 UTC, mMohsinSazim approved these changes

2024-07-14 12:31 UTC, merged